ccflags-y += -Idrivers/media/platform/msm/camera_v2_smartisan
ccflags-y += -Idrivers/media/platform/msm/camera_v2_smartisan/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_smartisan/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
