# Switch Class Driver
obj-$(CONFIG_SWITCH)		+= switch_class.o
obj-$(CONFIG_SWITCH_GPIO)	+= switch_gpio.o
ifdef CONFIG_VENDOR_SMARTISAN
obj-$(CONFIG_GPIO_COLOR)	+= gpio_color.o
endif

obj-$(CONFIG_SWITCH_ARIZONA)	+= switch-arizona.o
